---
title: "eda_1"
output: html_document
date: "2025-10-02"
---


```{r}
library(tidyverse)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

import the weather_df
```{r}
data("weather_df")

weather_df =
  weather_df |> 
  mutate(month = floor_date(date, unit = "month")) 
  #^rounding down e.g. March 16 to March 1 (round to day 1)
```

make plots

```{r}
weather_df |> 
  ggplot(aes(x=prcp)) +
  geom_histogram()
```

check on extreme values

```{r}
weather_df |> 
  filter(prcp>1000)
```

look at data again

```{r}
weather_df |> 
  filter(tmax >=20, tmax<=30) |> 
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) +
  geom_point()
```

Grouping! 

```{r}
weather_df |> 
  group_by(name, month) #can also group my month, by name and month, by name, etc.
```

group and count things

```{r}
weather_df |> 
  group_by(name) |> 
  summarize(
    n=n() #grouped by name, then summarizing how many observations per group
  )
```

```{r}
weather_df |> 
  group_by(month) |> 
  summarize(
    n = n_distinct(date) #counts up distinct instances, not just total #
  )
```

you can count directly

```{r}
weather_df |> 
  count(name) #counts up the # observations by name
```

##more interesting summaries

compute some extra stuff

```{r}
weather_df |> 
  group_by(month) |> 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE), #mean tmax in each month
    median_tmin = median(tmin, na.rm = TRUE),
    sd_prcp = sd(prcp, na.rm = TRUE)
  ) |> 
  view()
```

this is still a dataframe!!

```{r}
weather_df |> 
  group_by(name,month) |> 
  summarize(
    mean_tmax = mean(tmax, na.m = TRUE)
  ) |> 
  ggplot(aes(x = month, y = mean_tmax, color = name)) +
  geom_point() +
  geom_line()
```

sometimes format results more nicely

```{r}
weather_df |> 
  group_by(name, month) |> 
  summarize(
    mean_tmax = mean(tmax, na.m = TRUE)
  ) |> 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax
  ) |> 
  knitr::kable(digits = 2) #formats table into a nice structure. digits = 2 (2 decimals)
```

##mutate with groups

```{r}
weather_df |> 
  group_by(name) |> 
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE),
    center_tmax = tmax - mean_tmax
  ) |> 
  ggplot(aes(x = date, y = center_tmax, color = name)) +
  geom_point()
```

look for cold days

```{r}
weather_df |> 
  group_by(name,month) |> 
  mutate(temp_rank = min_rank(tmax)) |> #desc(tmin) would give you "hottest" coldest day
  filter(temp_rank < 2) #gives me coldest days by month by location
```

What about lags?

```{r}
weather_df |> 
  group_by(name) |> 
  mutate(lagged_tmax = lag(tmax)) #looking at tmax 1 day before
```

use the variables you create

```{r}
weather_df |> 
  group_by(name) |> 
  mutate(
    temp_change = tmax - lag(tmax)
  ) |> 
  summarize(
    sd_tmax_change = sd(temp_change, na.rm = TRUE),
    tmax_change_max = max(temp_change, na.rm = TRUE)
  )
```








